# 사이트 공통 설정
BASE_URL = "https://seocho-massage.netlify.app"

BRAND = "간다GO"
PHONE = "0508-202-4719"
PHONE_DISPLAY = "0508-202-4719"

# IndexNow 인증 키 — 빌드 시 루트에 <키>.txt 파일이 생성되고,
# indexnow_ping.py 가 빙·네이버 등 IndexNow 참여 엔진에 색인을 통보할 때 사용한다.
# (키는 공개되어도 무방한 값이다 — 프로토콜 설계상 키 파일이 곧 소유 증명)
INDEXNOW_KEY = "c3f8a6d92b714e05a1d7c4b8e2f95360"

# 상단 메뉴 — 하위 메뉴에는 키워드를 반복하지 않고 지역명·역명만 표시한다.
NAV = [
    ("홈", "/", []),
    ("서초 출장마사지", "/massage/", [
        ("출장마사지 안내", "/massage/#service"),
        ("홈타이 안내", "/massage/#hometai"),
        ("전지역 방문 안내", "/massage/#coverage"),
        ("지하철역 인근 안내", "/massage/#stations"),
        ("예약 가능 시간", "/massage/#hours"),
        ("코스 선택 안내", "/massage/#course"),
        ("이용 전 확인사항", "/massage/#check"),
        ("위생·안전 안내", "/massage/#safety"),
        ("자주 묻는 질문", "/massage/#faq"),
    ]),
    ("지역별 안내", "/seocho-gu/", [
        ("서초구 전체", "/seocho-gu/"),
        ("서초동", "/seocho-gu/seocho-dong/"),
        ("잠원동", "/seocho-gu/jamwon-dong/"),
        ("반포동", "/seocho-gu/banpo-dong/"),
        ("방배동", "/seocho-gu/bangbae-dong/"),
        ("양재동", "/seocho-gu/yangjae-dong/"),
        ("내곡동", "/seocho-gu/naegok-dong/"),
    ]),
    ("지하철역별 안내", "/seocho-gu/stations/", [
        ("역 전체", "/seocho-gu/stations/"),
        ("강남역", "/seocho-gu/stations/gangnam-station/"),
        ("교대역", "/seocho-gu/stations/gyodae-station/"),
        ("서초역", "/seocho-gu/stations/seocho-station/"),
        ("방배역", "/seocho-gu/stations/bangbae-station/"),
        ("사당역", "/seocho-gu/stations/sadang-station/"),
        ("잠원역", "/seocho-gu/stations/jamwon-station/"),
        ("고속터미널역", "/seocho-gu/stations/express-bus-terminal-station/"),
        ("남부터미널역", "/seocho-gu/stations/nambu-bus-terminal-station/"),
        ("양재역", "/seocho-gu/stations/yangjae-station/"),
        ("총신대입구역", "/seocho-gu/stations/chongshin-univ-station/"),
        ("동작역", "/seocho-gu/stations/dongjak-station/"),
        ("논현역", "/seocho-gu/stations/nonhyeon-station/"),
        ("반포역", "/seocho-gu/stations/banpo-station/"),
        ("내방역", "/seocho-gu/stations/naebang-station/"),
        ("이수역", "/seocho-gu/stations/isu-station/"),
        ("신논현역", "/seocho-gu/stations/sinnonhyeon-station/"),
        ("사평역", "/seocho-gu/stations/sapyeong-station/"),
        ("신반포역", "/seocho-gu/stations/sinbanpo-station/"),
        ("구반포역", "/seocho-gu/stations/gubanpo-station/"),
        ("양재시민의숲역", "/seocho-gu/stations/yangjae-citizens-forest-station/"),
        ("청계산입구역", "/seocho-gu/stations/cheonggyesan-station/"),
    ]),
    ("테마별 안내", "/themes/", [
        ("전체 테마", "/themes/"),
        ("스웨디시", "/themes/swedish/"),
        ("로미로미", "/themes/lomilomi/"),
        ("타이마사지", "/themes/thai/"),
        ("중국마사지", "/themes/chinese/"),
        ("아로마테라피", "/themes/aroma/"),
        ("홈케어", "/themes/homecare/"),
        ("호텔식마사지", "/themes/hotel-style/"),
        ("발마사지", "/themes/foot/"),
        ("스포츠·경락", "/themes/sports/"),
        ("스킨케어", "/themes/skincare/"),
        ("왁싱", "/themes/waxing/"),
        ("커플 관리", "/themes/couple/"),
        ("24시간", "/themes/24hours/"),
        ("수면 가능", "/themes/overnight/"),
    ]),
    ("코스안내", "/courses/", [
        ("전체 코스", "/courses/"),
        ("피로 회복 관리", "/courses/#recovery"),
        ("아로마 관리", "/courses/#aroma"),
        ("스포츠 관리", "/courses/#sports"),
        ("홈타이 코스", "/courses/#hometai"),
        ("커플·가족 방문 관리", "/courses/#couple"),
        ("기업·단체 방문 관리", "/courses/#group"),
        ("가격 안내", "/courses/#price"),
        ("코스 선택 가이드", "/courses/#guide"),
    ]),
    ("예약안내", "/reservation/", [
        ("예약 방법", "/reservation/#how"),
        ("예약 가능 시간", "/reservation/#hours"),
        ("방문 가능 장소", "/reservation/#place"),
        ("결제 안내", "/reservation/#payment"),
        ("변경·취소 안내", "/reservation/#change"),
        ("예약 전 체크사항", "/reservation/#check"),
    ]),
    ("이용가이드", "/guide/", [
        ("처음 이용하시는 분", "/guide/#first"),
        ("방문 전 준비사항", "/guide/#prepare"),
        ("위생 및 안전 기준", "/guide/#hygiene"),
        ("관리 후 주의사항", "/guide/#after"),
        ("금지행위 안내", "/guide/#prohibited"),
        ("이용 FAQ", "/guide/#faq"),
    ]),
    ("매거진", "/magazine/", [
        ("전체 글", "/magazine/"),
        ("아로마 vs 스웨디시", "/magazine/aroma-vs-swedish/"),
        ("사무직 목·어깨 관리", "/magazine/desk-worker-care/"),
        ("숙소 방문 이용 팁", "/magazine/hotel-stay-massage/"),
        ("등산 후 회복", "/magazine/hiking-recovery/"),
        ("커플 관리 준비", "/magazine/couple-home-massage/"),
        ("홈타이 공간 준비", "/magazine/home-thai-prep/"),
    ]),
    ("후기", "/reviews/", [
        ("전체 후기", "/reviews/"),
        ("지역별 후기", "/reviews/#area"),
        ("역세권 후기", "/reviews/#station"),
        ("후기 작성 안내", "/reviews/#write"),
    ]),
    ("고객센터", "/support/", [
        ("공지사항", "/support/#notice"),
        ("자주 묻는 질문", "/support/#faq"),
        ("1:1 문의", "/support/#contact"),
        ("제휴·기업 문의", "/support/#biz"),
        ("개인정보처리방침", "/support/privacy/"),
        ("이용약관", "/support/terms/"),
    ]),
]
